# Generated by Django 6.0.3 on 2026-03-20 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_progress'),
        ),
    ]
